### ISSUE TITLE
Set default EBS storage type to ST1 (configured similar to d2 instance types), allow GP2 as optional

### ISSUE THREAD

**Issue by santiagocardenas** [aws-quickstart/quickstart-confluent-kafka#16]

**Comment by dbtucker** [comment]
I'm open to suggestions regarding how to collect this information from the Customer.  

We could add an "EBS Storage Type" field, but it would be nice if the UI could properly test for invalid configurations.   We don't do that now, and some users run into difficulties when then specify "0 GB" of persistent store expecting instance store, but have selected an instance type that does not support that options.

**Comment by dbtucker** [comment]
What are the cost implications of defaulting to 2 TB of ST1 storage ?   The current default is 4 EBS volumes ... so the 500 GB min for ST1 means 2 TB minimum.   A bit of contortion on the framework COULD support a model where < 2TB would be 1 volume, < 4 TB would be 2 volumes, and then 4 volumes for any requested capacity more than than.   But that's separate from this issue.

Adding the flexibility select ST1, SC1, or GP2 volume types is relatively easy, but I'd like the defaults to not be overly expensive for users who won't need 2 TB / node of long-term storage.

**Comment by santiagocardenas** [comment]
We don't have to default to 2TB of storage, but default to ST1. Right now we aren't even using GP2 which is our standard in all newer regions. ST1 is less expensive than GP2.

**Comment by dbtucker** [comment]
So should the design have an option for "legacy"?   I only saw "gp2", "sc1", and "st1" as supported options for the VolumeType specification in the DeviceFileMapping details.   I can add a "NULL" option if necessary.

**Comment by santiagocardenas** [comment]
I think we should use what's recommended for Kafka workloads. Discussing with a few people internally, it seems that ST1 is the best option to start with. We can add GP2 as the additional option. Leaving the option null just uses whatever the AMI used for the image and the defaults in the region for additional volumes.

**Comment by dbtucker** [comment]
OK.   Sounds like having "NULL" (or blank) as an option to retain the region/ami default is reasonable.   Not terribly complex to handle in the template, and we can obviously set the defaults.

For now, I'll leave the boot disks alone (so they'll take on the default EBS volume type).   If I default to GP2 for the persistent storage for worker and zookeeper nodes, could that cause problems in any regions or with any instance type ?   I would rather not add 3 more parameters (persistent storage type for each of the three node classifications).

**Comment by dbtucker** [comment]
I have a quick update to the Quick Start Guide to describe this as well.   Let me know where to send that for proper publication.

**Comment by santiagocardenas** [comment]
@dbtucker,
Please feel free to email that to me and I can route it/include the right people.

Thanks,
Santiago
