### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by ssozonoff** [aws-quickstart/quickstart-confluent-kafka#23]
I have spent hours on this and is just not working as described in the documenations.

Instances get created but all the script files contain the following types of message

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>confluent-quickstart-reference</Bucket><Endpoint>confluent-quickstart-reference.s3.amazonaws.com</Endpoint><RequestId>B5164C4EC457281C</RequestId><HostId>DEWwatvTx/36B78Tuqr0eTx6Te7+Uf70XJZuZ2whB6XwcOVGPl+9C5dPkgLlmoYRkxHbDVOd290=</HostId></Error>
```

**Comment by santiagocardenas** [comment]
are you copying the Quick Start to your own bucket called (confluent-quickstart-reference)?

**Comment by ssozonoff** [comment]
I have tried it both ways.... I modified the template to change the S3 endpoint and that seemed to work but then it fails a little further down the line.....  I certainly did not expect it to be so hard after reading this https://s3.amazonaws.com/quickstart-reference/confluent/kafka/latest/doc/confluent-platform-on-the-aws-cloud.pdf

And debugging the issue's is just as difficult :-(

Thanks

**Comment by dbtucker** [comment]
@ssozonoff   Did you try the default deployment ... using the public S3 bucket that the AWS team maintains ?   It's a bit complicated to create a complete clone of the bucket (it requires not only the templates and deployment scripts but also the nested cloudformation template if you choose to create a new VPC on the fly).

**Comment by santiagocardenas** [comment]
As @dbtucker, the preferred deployment method initially is via the AWS provided bucket (quickstart-reference), which is what's referenced in the guide.

However, for making it your own, at this time you'd want to:
1. [optional] fork the repo
2. Ensure that you have an SSH key associated with your GitHub account
3. Clone recursively: `git clone --recursive git@github.com:aws-quickstart/quickstart-confluent-kafka.git`
4. Create your own S3 bucket in us-east-1 and add a bucket policy allowing public GetObject permissions
5. Sync the whole directory in an S3 key prefix via the AWS CLI: example with profile `aws s3 sync --profile my-profile . s3://my-public-bucket/confluent/kafka/` provided that you are in the root of the repo
6. Create a CloudFormation stack using the S3 Template URL for your master template: `https://my-public-bucket.s3.amazonaws.com/confluent/kafka/templates/confluent-kafka-master.template`

In the future we are looking into making these steps easier, like not requiring a public bucket or for the bucket to be in us-east-1.

**Comment by ssozonoff** [comment]
Thank you. I have this working now.

**Comment by miteshtrivedi10** [comment]
@ssozonoff @santiagocardenas 
guys can you help me? I am still facing the timeout issue. any guidance is appreciated.

**Comment by vsnyc** [comment]
@miteshtrivedi10 I have checked that the Quick Start is passing in our CI tests. Since this is a resolved issue, could you open a new one describing the error you are running into? Thanks.

**Comment by miteshtrivedi10** [comment]
@vsnyc Thanks I have this working now. Actually i am running in my organization aws account which is very much restricted with no connections allowed from internet, hence couls not run this seamlessly. Had to do some changes.

**Comment by vsnyc** [comment]
@miteshtrivedi10 Good to hear that, appreciate the confirmation.
