### ISSUE TITLE
XFS not found on Amazon Linux AMI

### ISSUE THREAD

**Issue by ssozonoff** [aws-quickstart/quickstart-confluent-kafka#26]
I will try with another AMI but it seems their is an issue when trying to deploy on the Amazon Linux AMI

++ mkfs -t xfs /dev/xvde
mkfs.xfs: No such file or directory

**Comment by dbtucker** [comment]
Thank you, @ssozonoff    We'll fix this ASAP.

**Comment by santiagocardenas** [comment]
Changes should be live now.
