### ISSUE TITLE
Make AssociatePublicIpAddress an optional flag

### ISSUE THREAD

**Issue by ssozonoff** [aws-quickstart/quickstart-confluent-kafka#29]
Its not always desirable to associate an external IP address.

**Comment by santiagocardenas** [comment]
@dbtucker Any thoughts on this?

@ssozonoff We welcome pull requests

Thanks,
Santiago

**Comment by dbtucker** [comment]
This should not be very difficult ... just a manner of making the "AssociatePublicIpAddress" setting within the nodegroup.template file parameterized.   

The only downside is that we'd keep adding more required inputs from users ... and we already have a fair number.

**Comment by ssozonoff** [comment]
This is always going to be the challenge. I have gone ahead and forked in order to adapt for our needs. Thanks

**Comment by petervandenabeele** [comment]
Hi @ssozonoff could you share the gist of your modification. I would also like to deploy in private subnets (and then access the Kafka cluster with a VPN to the VPC).

Thanks :-)
