### ISSUE TITLE
Launching to existing VPC - hostname in config fails to be resolved

### ISSUE THREAD

**Issue by madhurir12** [aws-quickstart/quickstart-confluent-kafka#57]
Launching into an existing vpc (without hostname DNS) fails, since the zookeeper & broker configs use hostname for server properties instead of private DNS or ip.

It would be ideal, if the scripts can expose a parameter to configure on if to use hostname's or private DNS or ip's for configuration.

**Comment by joncourt** [comment]
also se #45
