### ISSUE TITLE
The Open Source components aren't started

### ISSUE THREAD

**Issue by joncourt** [aws-quickstart/quickstart-confluent-kafka#58]
The guide implies that all the services are started after the deploy. I'm finding that's not the case with the open source version. On one of the brokers i do an `./opt/confluent/bin/confluent status` and get 
```
connect is [DOWN]
kafka-rest is [DOWN]
schema-registry is [DOWN]
kafka is [DOWN]
zookeeper is [DOWN]
```
is this expected?

**Comment by joncourt** [comment]
looks like a duplicate of #45 - the latter part where the components can't resolve the hosts by DNS but rather need IP. Working on a fix if possible.

**Comment by joncourt** [comment]
closing in favour of #45

**Comment by cyan-confluent** [comment]
Hello:

      So far as I can tell, all the required open source components are running and functioning. But you are right that confluent status does not report them as being up. This is because init scripts are not created on these aws templates, and the services don't conform to the format that /bin/confluent expects. 

Your best bet for checking which services are up, would be to do a `ps -ef | grep java` on the machines.

**Comment by joncourt** [comment]
thanks @cyan-confluent - i'll use the ps method instead.

i think in my case it's a similar issue to #45 where the hosts aren't being resolved by hostname and need ip. It's either something i'm missing in my vpc or i'll need to make it possible to resolve by IP in the components.
