### ISSUE TITLE
Requirement for selectable EBS storage

### ISSUE THREAD

**Issue by dbtucker** [aws-quickstart/quickstart-confluent-kafka#7]
Is it necessary for the template to allow the specification of different EBS storage types (and provisioned IOPS) for the deployment ?    Should this capability be available for the boot disk 
as well ?

Should the selection be allowed for brokers only ... or for Zookeeper and Worker nodes as well ?
And what about the case where zookeepers are provisioned alongside the broker service (in which case the zkdata directory is located on the boot disk rather than the data disks) ?

**Comment by santiagocardenas** [comment]
See #16 for more information on this. We should add options to allow ST1 volumes by default.
