### ISSUE TITLE
deployed but not working

### ISSUE THREAD

**Issue by dev-head** [aws-quickstart/quickstart-confluent-kafka#74]
cloud formation stack, open source v4, did not give me any output; per the docs step four will have the worker nodes with a webservice listening on :9021, this however is not working. I ssh'd into both worker nodes and neither of them have a service listening on that port. 

```
connect is [DOWN]
kafka-rest is [DOWN]
schema-registry is [DOWN]
kafka is [DOWN]
zookeeper is [DOWN]
```

looks like we can talk to the brokers/zookeeper from worker node, so somethings working. 

on the worker, here's the ports currently being listened too.
```
*:ssh     [root]  (sshd)  <TCP>
*:44903   [root]  (java)  <TCP>
*:tproxy  [root]  (java)  <TCP>
*:43168   [root]  (java)  <TCP>
*:8082    [root]  (java)  <TCP>
*:36679   [root]  (java)  <TCP>
*:8083    [root]  (java)  <TCP>
```

i'm not sure what else might help, i might just have to go back to the drawing board; this was my hail mary after ecs issues.

Thanks

**Comment by cyan-confluent** [comment]
The webservice listening on :9021 is the confluent control center, which is actually not part of Confluent open source. So if you chose the open source option, it'd not be installed by default.

Despite the output from the cli claiming the services are down, my guess is that all the OSS components are running. For example, from the port listing of :8082 and :8083, it looks like the connect framework is up.

Can you check the ports on the broker such as :9092 and zookeeper ports :2181, if it looks like these ports are up on their respective instances, the cluster is likely up and fully configured.

**Comment by dev-head** [comment]
welp, that would make sense. should be safe to redo this and not add the workers since they're only for the enterprise version. though, perhaps we'll test that out first for fun. anyhow, thank you for helping guide me along a bit.

**Comment by cyan-confluent** [comment]
I just want to make clear what each components does:

Zookeeper -- Does leader election, service discovery, stores metadata.
Broker -- Main Kafka heavy lifter, does the actual message passing, message storage.
Workers -- Runs the connector tasks that pull/push data into/out of kafka to your preferred integrations.

So even though you may not use Control Center in the open source version, you may still need to run workers if you are interested in running connectors. The Control Center just happens to run on workers in these templates to make the cluster more compact.
