### ISSUE TITLE
confluent quickstart on AWS timesout

### ISSUE THREAD

**Issue by polya20** [aws-quickstart/quickstart-confluent-kafka#78]
I have been trying to get the quickstart confluent kafka running in a local VPC but the worker nodes timeout  similar to https://github.com/aws-quickstart/quickstart-confluent-kafka/issues/77
Can someone confirm that the quickstart works fine in both configurations.

**Comment by cyan-confluent** [comment]
A fairly frequent issue people run into is that they forget to subscribe the the appropriate Linux AMIs in the marketplace before using the template. Can you check that you've done this? They are linked in step (2) of the "How to Deploy" Section on the AWS Quickstart site.

Can you also post your input parameters for the template, so I can reproduce with exact same configuration. 

Also, what do you mean by "local vpc", I'm assuming you mean "deploy into an existing vpc".

**Comment by polya20** [comment]
1. indeed this was the first thing I did after reading the solution from #77 and tried out both CentOS and AWSlinux instances.
2. Here is the errors: the full file is attached.
un 25 09:58:38 cloud-init[2844]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-0fe6844cd765fedb8/sem/config_scripts_user'>)
Jun 25 09:58:38 cloud-init[2844]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Jun 25 10:09:53 cloud-init[2844]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [127]
Jun 25 10:09:53 cloud-init[2844]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [127]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 644, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 1615, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 127
Reason: -
Stdout: ''
Stderr: ''
Jun 25 10:09:53 cloud-init[2844]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jun 25 10:09:53 cloud-init[2844]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Jun 25 10:09:53 cloud-init[2844]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 660, in _run_modules
    cc.run(run_name, mod.handle, func_args, freq=freq)
  File "/usr/lib/python2.7/dist-packages/cloudinit/cloud.py", line 63, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/dist-packages/cloudinit/helpers.py", line 197, in run
    results = functor(*args)
  File "/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 651, in runparts
    % (len(failed), len(attempted)))


cat /tmp/cp-install.err
/var/lib/cloud/instance/scripts/part-001: line 76: /tmp/sbin/cp-install.sh: No such file or directory
[ec2-user@ip-10-201-231-246 tmp]$ cat cp-deploy.err
/var/lib/cloud/instance/scripts/part-001: line 77: /tmp/sbin/cp-deploy.sh: No such file or directory

3. Configuration:
AssignPublicIP	true	
BootDiskSize	24	
BrokerNodeInstanceType	m4.xlarge	
BrokerNodeSpotPrice	0.00	
BrokerNodeStorage	512	
BrokerNodeStorageType	st1	
ClusterName	awsqs	
ConfluentEdition	Confluent Enterprise	
ConfluentVersion	4.0.0	
ConnectorURLs		
KeyPairName	confluent-kafka	
LinuxOSAMI	Amazon-Linux-HVM	
NumBrokers	3	
NumWorkers	2	
NumZookeepers	0	
QSS3BucketName	aws-quickstart	
QSS3KeyPrefix	quickstart-confluent-kafka/	
RemoteAccessCIDR	0.0.0.0/0	
SSHAccessCIDR	0.0.0.0/0	
SubnetID		
VPCID		
WorkerNodeInstanceType	m4.xlarge	
WorkerNodeSpotPrice	0.00	
WorkerNodeStorage	0	
ZookeeperNodeInstanceType	m4.large	
ZookeeperNodeSpotPrice	0.00	
ZookeeperNodeStorage	0

4. Indeed, I meant existing VPC.
[aws_new.txt](https://github.com/aws-quickstart/quickstart-confluent-kafka/files/2133147/aws_new.txt)

**Comment by polya20** [comment]
Maybe not important but the deployment was tried in the Ireland region

**Comment by polya20** [comment]
ok, i figured out the problem. It was with our local ACLs and not an issue with the script. Closing
