### ISSUE TITLE
does enterprise confluent need license 

### ISSUE THREAD

**Issue by polya20** [aws-quickstart/quickstart-confluent-kafka#79]
on deploying confluent enterprise on AWS, the confluent control center shows as "not running" and in the license tab  should N/A invalid date. Do I have to request license keys, I have just tried it for less than a week.

**Comment by cyan-confluent** [comment]
By default, you should have a 30-day trial license. Has it ever worked for you, or did it stop working suddenly?

**Comment by polya20** [comment]
It worked the first time and then when I deleted the stack and recreated a new one, it stopped. I am digging through the logs to find out the error.

**Comment by polya20** [comment]
although not solved, the logs suggest that there is a network issue, hence closing.
